name : pyhton_Application

on : 
  push : 
    paths : 
      C:\Users\RMCPDEDT024\Desktop\python_pro 
jobs : 
  build :
    runs-on: windows-latest
    steps :
      - name: Checkout code
        uses: actions/checkout@v4
      - name: python setup 
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: run python script
        run : python operations.py 
